---
title: "Color"
author: "Haotian Zheng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
"#ffffff"
# heatmap

c("#a673a3", "#a775a4", "#aa7aa7", "#af82ac", "#b58db3", "#be9bbc", "#c6a9c6", "#ceb7ce", "#d5c3d5", "#dcd0dd", "#e3dce4", "#e8e7e9", "#eaeeea", "#e9f1e6", "", "#e1f0d6", "#dbeecb", "#d6ecc1", "#d1eab6", "#cbe8aa", "#c5e59d", "#bfe292", "#b9df89", "#b3dc82", "#add97d", "#a6d579", "#a0d277", "#99ce76", "#92ca77", "#8bc67b", "#83c280", "#7cbd85", "#75b989", "#6eb58c", "#67b090", "#60ac93", "#59a795", "#54a296", "#509d95", "#4d9793", "#4a9190", "#478c8c", "#458689", "#428085", "#407981", "#3d737d", "#3b6e79", "#3a6a77", "#396876", "#396775"
)

c("#aa7aa7","#ceb7ce","#eaeeea","#d6ecc1","#b9df89","#99ce76","#75b989","#54a296","#458689","#3a6a77")

colors <- c("#aa7aa7", "#c88b9c", "#d4a29a", "#d6bca7", "#d8d4c1", "#cdd2c2", "#c4cfc3", "#beccc5", "#9cb3ad", "#7a9b99", "#598287", "#3a6a77")

c("#351540", "#422B77", "#3B4C88", "#30688D", "#25848C", "#269E84","#35B777", "#72CB54", "#B3DB37", "#F8E620")

# few color

## standard paris olympic color.
c("#BF7EA2","#BF9FB1","#1E2040","#0F7BA6","#BFAB6F")

## the color match paris olympic but not the same.
c("#23496d","#8b68ab","# ","#7396bf","#87be5f")

c("#b2dba7","#bfa8cd","#6d2b80")

c("#F9B0E2","#14BEBD","#0B2E55")


# stack plot color 20
colors <- c("#c0dbe6","#2b526f","#4a9ba7","#a3cbd6","#c0cfbd","#9bb88a","#7b9b64","#d0cab7","#c6a4c5","#9b7baa","#7a7aaf","#434d91","#5284a2","#82b4c8","#9d795d","#d1b49a","#fff08c","#e1834e","#cd6073","#ffc7c9","#969696","#d1d9e2")

# new color list based on before.

## main colors

color_htmap <- c("#8fced1", "#8ac2cd", "#86b7c8", "#81abc4", "#7ca0c0", "#7894bb", "#7389b7", "#6e7db3", "#6a72ae", "#6566aa")

colors_new_four <- c("#6566aa", "#8fced1", "#f07e40", "#dc5772")

colors_new_20 <- c("#434d91","#6566aa","#9b7baa","#c6a4c5","#c6f0ec","#8fced1","#53a4a6","#d0cab7","#c0dbe6","#509d95","#75b989","#92ca77","#d6ecc1","#e7ee9f","#f7ded5","#faaf7f","#f07e40","#dc5772","#ebc1d1","#f9e7e7","#969696","#d1d9e2")

colors_new_20_taxa <- c("#6566aa","#c6a4c5","#c6f0ec","#8fced1","#53a4a6","#d0cab7","#c0dbe6","#9bb88a","#75b989","#92ca77","#d6ecc1","#e7ee9f","#f7ded5","#faaf7f","#f07e40","#dc5772","#ebc1d1","#f9e7e7","#decba1","#d4888b","#969696","#d1d9e2")


"#8fced1", "#8ac2cd", "#86b7c8", "#81abc4", "#7ca0c0", "#7894bb", "#7389b7", "#6e7db3", "#6a72ae", "#6566aa", "#5b4fa1", "#513798", "#47208f", "#3d0886", "#33007d"

"#8fced1", "#86b7c8", "#7ca0c0", "#7389b7", "#6a72ae", "#5b4fa1", "#513798", "#47208f", "#3d0886", "#33007d"

"#434d91"="RM", "#6566aa"="SoFic", "#9b7baa"="PD_T4_6", "#c6a4c5"="CRISPRCas", "#c6f0ec"="AbiE", "#8fced1"="Zorya", "#53a4a6"="Septu", "#d0cab7"="Wadjet", "#c0dbe6"="CBASS", "#509d95"="AbiD", "#75b989"="DRT", "#92ca77"="AbiL", "#d6ecc1"="Gabija", "#e7ee9f"="Mokosh", "#f7ded5"="dXTPase", "#faaf7f"="GAO_19", "#f07e40"="Paris", "#dc5772"="darTG", "#ebc1d1"="ietAS", "#f9e7e7"="RosmerTA", "#d1d9e2"="Others"

"#434d91"="SoFic", "#6566aa"="PD_T4_6", "#9b7baa"="RM_II", "#c6a4c5"="AbiE", "#c6f0ec"="RM_IIG", "#8fced1"="CRISPRCas_Other", "#53a4a6"="RM_I", "#d0cab7"="Septu_I", "#c0dbe6"="Cas_Adaptation", "#509d95"="AbiD", "#75b989"="Wadjet_Other", "#92ca77"="Zorya_Other", "#d6ecc1"="AbiL", "#e7ee9f"="RM_IV", "#f7ded5"="Gabija", "#faaf7f"="RM_III", "#f07e40"="Cbass_I", "#dc5772"="dXTPase", "#ebc1d1"="DRT_II", "#f9e7e7"="GAO_19", "#d1d9e2"="Others"
```
