---
title: "Upset"
author: "Haotian Zheng"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(UpSetR)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
```

# Country
```{r}
data <- read.csv("Collect/All_defense_info_sing.csv")

data <- data %>% mutate(Country_Group = Country)

binary_matrix <- data %>%
  distinct(Country_Group, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

binary_matrix <- binary_matrix %>% column_to_rownames("Country_Group")

binary_matrix <- as.data.frame(t(binary_matrix))

binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

custom_order <- colnames(binary_matrix)
binary_matrix <- binary_matrix %>% select(all_of(custom_order))

png("Results/02_DF_distribution/02_Upset_new/upset_plot_country.png", 
    width = 5, height = 5, units = "in", res = 600)

upset(binary_matrix, 
      sets = colnames(binary_matrix)[-1],
      order.by = "freq", 
      keep.order = TRUE,
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```

## Location
```{r}
# Read data
data <- read.csv("Collect/All_defense_info_sing.csv")

# Use Location as the grouping column
data <- data %>% mutate(Location_Group = Location)

# Create binary matrix of defense types
binary_matrix <- data %>%
  distinct(Location_Group, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

# Set Location_Group as row names
binary_matrix <- binary_matrix %>% column_to_rownames("Location_Group")

# Transpose matrix and ensure result is a data frame
binary_matrix <- as.data.frame(t(binary_matrix))

# Ensure column and row names are correct
binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

# Sort columns
custom_order <- colnames(binary_matrix)
binary_matrix <- binary_matrix %>% select(all_of(custom_order))

# Save plot
png("Results/02_DF_distribution/02_Upset_new/upset_plot_location.png", 
    width = 5, height = 5, units = "in", res = 600)

# Draw Upset plot
upset(binary_matrix, 
      sets = colnames(binary_matrix)[-1],
      order.by = "freq", 
      keep.order = TRUE,
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```

## Genome Location
```{r}
data <- read.csv("Collect/All_defense_info_sing.csv")

data <- data %>% mutate(Contig_Group = Contig_Classification)

binary_matrix <- data %>%
  distinct(Contig_Group, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

binary_matrix <- binary_matrix %>% column_to_rownames("Contig_Group")

binary_matrix <- as.data.frame(t(binary_matrix))

binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

custom_order <- colnames(binary_matrix)
binary_matrix <- binary_matrix %>% select(all_of(custom_order))

png("Results/02_DF_distribution/02_Upset_new/upset_plot_genome_location.png", 
    width = 5, height = 5, units = "in", res = 600)

upset(binary_matrix, 
      sets = colnames(binary_matrix)[-1],
      order.by = "freq", 
      keep.order = TRUE,
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```

## Country + Location
```{r}
data <- read.csv("Collect/All_defense_info_sing.csv")

data <- data %>% mutate(Country_Location = paste(Country, Location, sep = "_"))

binary_matrix <- data %>%
  distinct(Country_Location, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

binary_matrix <- binary_matrix %>% column_to_rownames("Country_Location")

binary_matrix <- as.data.frame(t(binary_matrix))

binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

custom_order <- c("UK_BTP", "SP_BTP", "DK_BTP", "UK_MS", "SP_MS", "DK_MS", "UK_RS", "SP_RS", "DK_RS", "UK_HP", "SP_HP", "DK_HP")
binary_matrix <- binary_matrix %>% select(Defense_Type, all_of(custom_order))

png("Results/02_DF_distribution/02_Upset_new/upset_plot_country_location.png", 
    width = 5, height = 5, units = "in", res = 600)

upset(binary_matrix, 
      sets = custom_order,
      keep.order = TRUE,
      order.by = "degree",
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```

## Country + Genome Location
```{r}
data <- read.csv("Collect/All_defense_info_sing.csv")

data <- data %>% mutate(Country_Location = paste(Country, Contig_Classification, sep = "_"))

binary_matrix <- data %>%
  distinct(Country_Location, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

binary_matrix <- binary_matrix %>% column_to_rownames("Country_Location")

binary_matrix <- as.data.frame(t(binary_matrix))

binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

custom_order <- c("Defense_Type", "UK_Plasmid", "UK_Chromosome", "SP_Plasmid", "SP_Chromosome", "DK_Plasmid", "DK_Chromosome")

binary_matrix <- binary_matrix %>% select(all_of(custom_order))

binary_matrix <- binary_matrix %>%
  rename(UK_P = UK_Plasmid, UK_C = UK_Chromosome, SP_P = SP_Plasmid, SP_C = SP_Chromosome, DK_P = DK_Plasmid, DK_C = DK_Chromosome)

png("Results/02_DF_distribution/02_Upset_new/upset_plot_country_genomelocation.png", 
    width = 5, height = 5, units = "in", res = 600)

upset(binary_matrix, 
      sets = colnames(binary_matrix)[-1],
      order.by = "freq", 
      keep.order = TRUE,
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```

# Location + Genome Location
```{r}
data <- read.csv("Collect/All_defense_info_sing.csv")

data <- data %>% mutate(Group = paste(Location, Contig_Classification, sep = "_"))

binary_matrix <- data %>%
  distinct(Group, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

binary_matrix <- binary_matrix %>% column_to_rownames("Group")

binary_matrix <- as.data.frame(t(binary_matrix))

binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

custom_order <- c("Defense_Type", "BTP_Phage", "MS_Phage", "RS_Phage", "HP_Phage", 
                  "BTP_Plasmid", "MS_Plasmid", "RS_Plasmid", "HP_Plasmid", 
                  "BTP_Chromosome", "MS_Chromosome", "RS_Chromosome", "HP_Chromosome")
binary_matrix <- binary_matrix %>% select(all_of(custom_order))

png("Results/02_DF_distribution/02_Upset_new/upset_plot_location_genomelocation.png", 
    width = 5, height = 5, units = "in", res = 600)

upset(binary_matrix, 
      sets = colnames(binary_matrix)[-1],
      order.by = "freq", 
      keep.order = TRUE,
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```

# Country + Location BAF + Genome Location
```{r}
data <- read.csv("Collect/All_defense_info_sing.csv")

data <- data %>% mutate(Group = paste(Country, Location_BAF, Contig_Classification, sep = "_"))

binary_matrix <- data %>%
  distinct(Group, Defense_Type) %>%
  mutate(present = 1) %>%
  pivot_wider(names_from = Defense_Type, values_from = present, values_fill = 0)

binary_matrix <- binary_matrix %>% column_to_rownames("Group")

binary_matrix <- as.data.frame(t(binary_matrix))

binary_matrix <- binary_matrix %>% rownames_to_column(var = "Defense_Type")

custom_order <- c("Defense_Type", "UK_After_Filter_Plasmid", "SP_After_Filter_Plasmid", "DK_After_Filter_Plasmid", "UK_After_Filter_Chromosome", "SP_After_Filter_Chromosome", "DK_After_Filter_Chromosome", "UK_Before_Filter_Plasmid", "SP_Before_Filter_Plasmid", "DK_Before_Filter_Plasmid", "UK_Before_Filter_Chromosome", "SP_Before_Filter_Chromosome", "DK_Before_Filter_Chromosome")
binary_matrix <- binary_matrix %>% select(all_of(custom_order))

binary_matrix <- binary_matrix %>%
  rename(UK_AF_P = UK_After_Filter_Plasmid, SP_AF_P = SP_After_Filter_Plasmid, DK_AF_P = DK_After_Filter_Plasmid, UK_AF_C = UK_After_Filter_Chromosome, SP_AF_C = SP_After_Filter_Chromosome, DK_AF_C = DK_After_Filter_Chromosome, 
         UK_BF_P = UK_Before_Filter_Plasmid, SP_BF_P = SP_Before_Filter_Plasmid, DK_BF_P = DK_Before_Filter_Plasmid, UK_BF_C = UK_Before_Filter_Chromosome, SP_BF_C = SP_Before_Filter_Chromosome, DK_BF_C = DK_Before_Filter_Chromosome)

png("Results/02_DF_distribution/02_Upset_new/upset_plot_country_locationbaf_genomelocation.png", 
    width =12, height = 6, units = "in", res = 600)

upset(binary_matrix, 
      sets = colnames(binary_matrix)[-1],
      order.by = "freq", 
      keep.order = TRUE,
      main.bar.color = "#BF7EA2",
      sets.bar.color = "#0F7BA6")

dev.off()
```



